export enum CreateUserRequestErrors {
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_AGE = 'INVALID_AGE',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_IMAGE = 'INVALID_IMAGE',
  INVALID_NAME = 'INVALID_NAME',
  INVALID_PROFILE = 'INVALID_PROFILE',
}