export enum CreateUserRequestErrors {
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_BIRTHDATE = 'INVALID_BIRTHDATE',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_NAME = 'INVALID_NAME',
  INVALID_PROFILE = 'INVALID_PROFILE',
}